# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.cache/wt [current_project]
set_property parent.project_path C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/code.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/ahb3lite_pkg.sv
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/ahb3lite_interconnect.sv
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/ahb3lite_interconnect_master_port.sv
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/ahb3lite_interconnect_slave_port.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/CORTEXM0INTEGRATION.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/ahb_rom.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_bitband.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_cs_rom_table.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_default_slave.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_gpio.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_master_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_slave_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_to_apb.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_to_iop.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_dualtimers_defs.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_dualtimers.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_dualtimers_frc.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_slave_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_subsystem_m0ds.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_test_slave.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_timer.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_uart.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_watchdog_defs.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_watchdog.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_apb_watchdog_frc.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_clock_gate.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_iop_gpio.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_irq_sync.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_defs.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/fpga_options_defs.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_ahb_memory_models_defs.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_addr_decode.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_clkctrl.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_pin_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_stclkctrl.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_sysctrl.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu_system.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cortexm0ds_logic.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_defines.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_apb_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ahbm_rd.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ahbm_timeout.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ahbm_wr.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_arbiter.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_calc.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_calc_addr.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_calc_joint.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_calc_size.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_empty.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_fifo.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_fifo_ctrl.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_fifo_ptr.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_offsets.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_outs.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_periph_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_rd_slicer.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_ch_reg_params.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_reg.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_reg_size.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_remain.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ch_wr_slicer.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_channels.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_channels_apb_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_channels_mux.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_ctrl.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_top.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_core0_wdt.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_dual_core.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_reg_params.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_reg.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/dma_ahb32_reg_core0.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_delay.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_demux8.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_fifo.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_joint_stall.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_min2.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_min3.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_mux8.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_or8.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_rawstat.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_scatter8_1.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_stall.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/prgen_swap_32.v
  C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu/cmsdk_mcu.v
}
read_ip -quiet C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.srcs/sources_1/ip/ahblite_axi_bridge_0/ahblite_axi_bridge_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Home/Desktop/cmsdk_mcu/cmsdk_mcu.srcs/sources_1/ip/ahblite_axi_bridge_0/ahblite_axi_bridge_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cmsdk_mcu -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cmsdk_mcu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cmsdk_mcu_utilization_synth.rpt -pb cmsdk_mcu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
